sudo: false

language: haskell

ghc: "8.2.2"

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store

install:
  - cabal install happy
  - cabal install --only-dependencies --enable-tests --allow-newer