sudo: true

services:
  - postgresql

language: haskell

ghc: "8.2.2"

cache:
  directories:
    - $HOME/.cabal/
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  - stack setup
  - stack build --only-dependencies -j1
  - stack build --copy-bins --test --no-run-tests
  - stack build dbmigrations-postgresql --stack-yaml migrations.yaml
  - psql -c 'create database snap;' -U postgres
  - stack exec moo-postgresql upgrade
  

install:
  - stack install

script:
  - stack test