name:                snap-example
version:             1.0.3
github:              "kinorius123/snap"
license:             BSD3
author:              "Esteban Ibarra"
maintainer:          "kinorius123@github.com"
copyright:           "2018 Esteban Ibarra"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/kinorius123/snap#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - mtl
  - snap
  - snap-core
  - snap-server
  - snaplet-postgresql-simple
  - postgresql-simple
  - Decimal
  - transformers
  - lens
  - text
  - time

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -Werror
    
executables:
  snap-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snap-example
    - snap

tests:
  snap-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snap-example
    - hspec
